#ifndef CNOID_GLCAMERAEFFECTPLUGIN_EXPORTDECL_H_INCLUDED
#define CNOID_GLCAMERAEFFECTPLUGIN_EXPORTDECL_H_INCLUDED

#if defined _WIN32 || defined __CYGWIN__
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLIMPORT __declspec(dllimport)
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLEXPORT __declspec(dllexport)
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLLOCAL
#else
#if __GNUC__ >= 4
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLIMPORT \
    __attribute__((visibility("default")))
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLEXPORT \
    __attribute__((visibility("default")))
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLLOCAL \
    __attribute__((visibility("hidden")))
#else
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLIMPORT
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLEXPORT
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLLOCAL
#endif
#endif

#ifdef CNOID_GLCAMERAEFFECTPLUGIN_STATIC
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLAPI
#define CNOID_GLCAMERAEFFECTPLUGIN_LOCAL
#else
#ifdef CnoidGLCameraEffectPlugin_EXPORTS
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLAPI \
    CNOID_GLCAMERAEFFECTPLUGIN_DLLEXPORT
#else
#define CNOID_GLCAMERAEFFECTPLUGIN_DLLAPI \
    CNOID_GLCAMERAEFFECTPLUGIN_DLLIMPORT
#endif
#define CNOID_GLCAMERAEFFECTPLUGIN_LOCAL \
    CNOID_GLCAMERAEFFECTPLUGIN_DLLLOCAL
#endif

#endif

#ifdef CNOID_EXPORT
#undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_GLCAMERAEFFECTPLUGIN_DLLAPI
