#ifndef CNOID_SIMPLECONTROLLERPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_SIMPLECONTROLLERPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_SIMPLECONTROLLERPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_SIMPLECONTROLLERPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_SIMPLECONTROLLERPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_SIMPLECONTROLLERPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_SIMPLECONTROLLERPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_SIMPLECONTROLLERPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_SIMPLECONTROLLERPLUGIN_DLLIMPORT
#   define CNOID_SIMPLECONTROLLERPLUGIN_DLLEXPORT
#   define CNOID_SIMPLECONTROLLERPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_SIMPLECONTROLLERPLUGIN_STATIC
#  define CNOID_SIMPLECONTROLLERPLUGIN_DLLAPI
#  define CNOID_SIMPLECONTROLLERPLUGIN_LOCAL
# else
#  ifdef CnoidSimpleControllerPlugin_EXPORTS
#   define CNOID_SIMPLECONTROLLERPLUGIN_DLLAPI CNOID_SIMPLECONTROLLERPLUGIN_DLLEXPORT
#  else
#   define CNOID_SIMPLECONTROLLERPLUGIN_DLLAPI CNOID_SIMPLECONTROLLERPLUGIN_DLLIMPORT
#  endif
#  define CNOID_SIMPLECONTROLLERPLUGIN_LOCAL CNOID_SIMPLECONTROLLERPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_SIMPLECONTROLLERPLUGIN_DLLAPI
