  
#ifndef CNOID_ROBOTACCESSPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_ROBOTACCESSPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_ROBOTACCESSPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_ROBOTACCESSPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_ROBOTACCESSPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_ROBOTACCESSPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_ROBOTACCESSPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_ROBOTACCESSPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_ROBOTACCESSPLUGIN_DLLIMPORT
#   define CNOID_ROBOTACCESSPLUGIN_DLLEXPORT
#   define CNOID_ROBOTACCESSPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_ROBOTACCESSPLUGIN_STATIC
#  define CNOID_ROBOTACCESSPLUGIN_DLLAPI
#  define CNOID_ROBOTACCESSPLUGIN_LOCAL
# else
#  ifdef CnoidRobotAccessPlugin_EXPORTS
#   define CNOID_ROBOTACCESSPLUGIN_DLLAPI CNOID_ROBOTACCESSPLUGIN_DLLEXPORT
#  else
#   define CNOID_ROBOTACCESSPLUGIN_DLLAPI CNOID_ROBOTACCESSPLUGIN_DLLIMPORT
#  endif
#  define CNOID_ROBOTACCESSPLUGIN_LOCAL CNOID_ROBOTACCESSPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_ROBOTACCESSPLUGIN_DLLAPI
