#ifndef CNOID_ASSIMP_SCENE_WRITER_EXPORTDECL_H_INCLUDED
# define CNOID_ASSIMP_SCENE_WRITER_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_ASSIMP_SCENE_WRITER_DLLIMPORT __declspec(dllimport)
#  define CNOID_ASSIMP_SCENE_WRITER_DLLEXPORT __declspec(dllexport)
#  define CNOID_ASSIMP_SCENE_WRITER_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_ASSIMP_SCENE_WRITER_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_ASSIMP_SCENE_WRITER_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_ASSIMP_SCENE_WRITER_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_ASSIMP_SCENE_WRITER_DLLIMPORT
#   define CNOID_ASSIMP_SCENE_WRITER_DLLEXPORT
#   define CNOID_ASSIMP_SCENE_WRITER_DLLLOCAL
#  endif
# endif

# ifdef CNOID_ASSIMP_SCENE_WRITER_STATIC
#  define CNOID_ASSIMP_SCENE_WRITER_DLLAPI
#  define CNOID_ASSIMP_SCENE_WRITER_LOCAL
# else
#  ifdef CnoidAssimpSceneWriter_EXPORTS
#   define CNOID_ASSIMP_SCENE_WRITER_DLLAPI CNOID_ASSIMP_SCENE_WRITER_DLLEXPORT
#  else
#   define CNOID_ASSIMP_SCENE_WRITER_DLLAPI CNOID_ASSIMP_SCENE_WRITER_DLLIMPORT
#  endif
#  define CNOID_ASSIMP_SCENE_WRITER_LOCAL CNOID_ASSIMP_SCENE_WRITER_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_ASSIMP_SCENE_WRITER_DLLAPI
