
#ifndef CNOID_PYTHON_INTERPRETER_EXPORTDECL_H_INCLUDED
# define CNOID_PYTHON_INTERPRETER_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_PYTHON_INTERPRETER_DLLIMPORT __declspec(dllimport)
#  define CNOID_PYTHON_INTERPRETER_DLLEXPORT __declspec(dllexport)
#  define CNOID_PYTHON_INTERPRETER_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_PYTHON_INTERPRETER_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_PYTHON_INTERPRETER_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_PYTHON_INTERPRETER_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_PYTHON_INTERPRETER_DLLIMPORT
#   define CNOID_PYTHON_INTERPRETER_DLLEXPORT
#   define CNOID_PYTHON_INTERPRETER_DLLLOCAL
#  endif
# endif

# ifdef CNOID_PYTHON_INTERPRETER_STATIC
#  define CNOID_PYTHON_INTERPRETER_DLLAPI
#  define CNOID_PYTHON_INTERPRETER_LOCAL
# else
#  ifdef CnoidPythonInterpreter_EXPORTS
#   define CNOID_PYTHON_INTERPRETER_DLLAPI CNOID_PYTHON_INTERPRETER_DLLEXPORT
#  else
#   define CNOID_PYTHON_INTERPRETER_DLLAPI CNOID_PYTHON_INTERPRETER_DLLIMPORT
#  endif
#  define CNOID_PYTHON_INTERPRETER_LOCAL CNOID_PYTHON_INTERPRETER_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_PYTHON_INTERPRETER_DLLAPI
