#ifndef OPENHRP_ONLINE_VIEWER_IDL_INCLUDED
#define OPENHRP_ONLINE_VIEWER_IDL_INCLUDED

#include <cnoid/corba/OpenHRP/3.1/OpenHRPCommon.idl>

module OpenHRP {

  /**
   * @if jp
   * OnlineViewer インターフェース
   *
   * GrxUI の 3DView をクライアントプログラムから表示させる際に使用します。
   *
   * load() で読み込んだモデルに対して update() で情報を与えることでアニメーションします。
   *
   * また、 update() を使用すると情報は記録され、後で再生することもできます。
   */
  interface OnlineViewer {
	
	exception OnlineViewerException
    {
      /**
         @if jp
         エラーの説明
         @endif
      */
      string  description;
    };

    /**
     * @if jp
     * 表示内容を更新します
     *
     * 内容は記録され、後で再生し直すことができます。
     * @param state 更新する表示内容の情報
     * @else
     * Update Display
     * @endif
     */
    void update(in WorldState state);

    /**
     * @if jp
     * モデルの読み込みを行います。
     * @param name モデル名
     * @param url モデルファイルURL
     * @endif 
     */
    void load(in string name, in string url) raises (OnlineViewerException);

    /**
     * @if jp
     * 記録されたいままでの更新をクリアします。
     * @endif
     */
    void clearLog();

    /**
     * @if jp
     * データをクリアします。
     * @endif
     */
    void clearData();

    /**
     * @if jp
     * 表示内容を更新します。 update() とは違い、更新内容を記録しません。
     * @param state 更新する表示内容の情報
     * @else
     * state display without recording  '03 Apr.4  s.kajita
     * @endif
     */
    void drawScene(in WorldState state);

    /**
     * @if jp
     * 線の幅を設定します。
     * @endif
     */
    void setLineWidth(in float width);

    /**
     * @if jp
     * スケールを設定します。
     * @endif
     */
    void setLineScale(in float scale);

    /**
     * @if jp
     * 
     * @endif
     */
    boolean getPosture(in string robotId, out DblSequence posture);

    /**
     * @if jp
     * ログの保存先(WorldStateItem)を設定します。
     * 指定した名前のWorldStateItemが存在しない場合は新たに作成します。
     * @param name WorldStateItemの名前
     * @endif
     */
    void setLogName(in string name);

  };
  
};

#endif
