// -*- mode: idl; indent-tabs-mode: nil; tab-width: 4; c-basic-offset: 4; -*-
#ifndef OPENHRP_WORLD_IDL_INCLUDED
#define OPENHRP_WORLD_IDL_INCLUDED

#include <cnoid/corba/OpenHRP/3.1/ModelLoader.idl>

module OpenHRP {
    /**
     * @if jp
     * シミュレーション世界
     * @endif
     */
    interface World
    {
        /**
         * @if jp
         * @brief キャラクターを登録する
         * 
         * ModelLoader から得られた情報でキャラクタを登録します。
         * @param name シミュレーションでのキャラクタ名
         * @param cinfo ModelLoader から得られる CharacterInfo
         * @else
         * Register a character
         * @param   name    Object Character Name for Simulation
         * @param   cinfo   CharacterInfo
         * @endif
         */
        void registerCharacter(in string name, in BodyInfo cinfo);

    };

};

#endif
