.TH CHOREONOID 1

.SH NAME

choreonoid \- an integrated robotics GUI environment

.SH SYNOPSIS

.B choreonoid [OPTIONS]

.SH DESCRIPTION

Choreonoid is an integrated robotics GUI environment, which allows
users to add their own functions on the basis of various basic
robotics functions.

.SH OPTIONS

.TP 5
\-\-project arg
load a project file
.TP 5
\-\-start\-playback
start playback automatically
.TP 5
\-\-model arg
load a 3d model file
.TP 5
\-\-hrpmodel arg
load an OpenHRP model file
.TP 5
\-h, \-\-help
show help message

.SH AUTHOR

Shin'ichiro Nakaoka and Choreonoid Development Team, AIST.
