  
#ifndef CNOID_HRPSYS31PLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_HRPSYS31PLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_HRPSYS31PLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_HRPSYS31PLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_HRPSYS31PLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_HRPSYS31PLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_HRPSYS31PLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_HRPSYS31PLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_HRPSYS31PLUGIN_DLLIMPORT
#   define CNOID_HRPSYS31PLUGIN_DLLEXPORT
#   define CNOID_HRPSYS31PLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_HRPSYS31PLUGIN_STATIC
#  define CNOID_HRPSYS31PLUGIN_DLLAPI
#  define CNOID_HRPSYS31PLUGIN_LOCAL
# else
#  ifdef CnoidHrpsys31Plugin_EXPORTS
#   define CNOID_HRPSYS31PLUGIN_DLLAPI CNOID_HRPSYS31PLUGIN_DLLEXPORT
#  else
#   define CNOID_HRPSYS31PLUGIN_DLLAPI CNOID_HRPSYS31PLUGIN_DLLIMPORT
#  endif
#  define CNOID_HRPSYS31PLUGIN_LOCAL CNOID_HRPSYS31PLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_HRPSYS31PLUGIN_DLLAPI
