.TH CHOREONOID 1

.SH NAME

Choreonoid \- An extensible virtual robot environment built on an
integrated GUI framework

.SH SYNOPSIS

.B choreonoid [OPTIONS]

.SH DESCRIPTION

Choreonoid is a robotics GUI tool which allows users to handle virtual
robots and add various functions cooperating with the existing functions.

.SH OPTIONS

.TP 5
\-\-project arg
load a project file
.TP 5
\-\-start\-playback
start playback automatically
.TP 5
\-\-model arg
load a 3d model file
.TP 5
\-\-hrpmodel arg
load an OpenHRP model file
.TP 5
\-h, \-\-help
show help message

.SH AUTHOR

Shin'ichiro Nakaoka and Choreonoid Development Team, AIST.
