/**
   @author Japan Atomic Energy Agency
*/

#ifndef CNOID_TRAFFICCONTROLPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_TRAFFICCONTROLPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_TRAFFICCONTROLPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_TRAFFICCONTROLPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_TRAFFICCONTROLPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_TRAFFICCONTROLPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_TRAFFICCONTROLPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_TRAFFICCONTROLPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_TRAFFICCONTROLPLUGIN_DLLIMPORT
#   define CNOID_TRAFFICCONTROLPLUGIN_DLLEXPORT
#   define CNOID_TRAFFICCONTROLPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_TRAFFICCONTROLPLUGIN_STATIC
#  define CNOID_TRAFFICCONTROLPLUGIN_DLLAPI
#  define CNOID_TRAFFICCONTROLPLUGIN_LOCAL
# else
#  ifdef CnoidTrafficControlPlugin_EXPORTS
#   define CNOID_TRAFFICCONTROLPLUGIN_DLLAPI CNOID_TRAFFICCONTROLPLUGIN_DLLEXPORT
#  else
#   define CNOID_TRAFFICCONTROLPLUGIN_DLLAPI CNOID_TRAFFICCONTROLPLUGIN_DLLIMPORT
#  endif
#  define CNOID_TRAFFICCONTROLPLUGIN_LOCAL CNOID_TRAFFICCONTROLPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_TRAFFICCONTROLPLUGIN_DLLAPI
