#ifndef CNOID_MULTICOPTERPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_MULTICOPTERPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_MULTICOPTERPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_MULTICOPTERPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_MULTICOPTERPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_MULTICOPTERPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_MULTICOPTERPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_MULTICOPTERPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_MULTICOPTERPLUGIN_DLLIMPORT
#   define CNOID_MULTICOPTERPLUGIN_DLLEXPORT
#   define CNOID_MULTICOPTERPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_MULTICOPTERPLUGIN_STATIC
#  define CNOID_MULTICOPTERPLUGIN_DLLAPI
#  define CNOID_MULTICOPTERPLUGIN_LOCAL
# else
#  ifdef CnoidMulticopterPlugin_EXPORTS
#   define CNOID_MULTICOPTERPLUGIN_DLLAPI CNOID_MULTICOPTERPLUGIN_DLLEXPORT
#  else
#   define CNOID_MULTICOPTERPLUGIN_DLLAPI CNOID_MULTICOPTERPLUGIN_DLLIMPORT
#  endif
#  define CNOID_MULTICOPTERPLUGIN_LOCAL CNOID_MULTICOPTERPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_MULTICOPTERPLUGIN_DLLAPI
