
#ifndef CNOID_CAMERA_IMAGE_IDL_INCLUDED
#define CNOID_CAMERA_IMAGE_IDL_INCLUDED

/*
  The following definitions are extracted from OpenRTM-aist and hrpsys-base
*/
#include <BasicDataType.idl>

module Img {

typedef double Vec3[3];
typedef double Mat44[4][4];


enum ColorFormat
{
  CF_UNKNOWN, CF_GRAY, CF_RGB,
  CF_GRAY_JPEG, CF_RGB_JPEG // local extension
};


struct ImageData
{
  long width;
  long height;
  ColorFormat format;
  sequence<octet> raw_data;
};


struct CameraIntrinsicParameter
{
  double matrix_element[5];
  sequence<double> distortion_coefficient;
};


struct CameraImage
{
  RTC::Time captured_time;
  ImageData image;
  CameraIntrinsicParameter intrinsic;
  Mat44 extrinsic;
};


struct TimedCameraImage
{
  RTC::Time tm;
  CameraImage data;
  long error_code;
};

};

#endif
