#ifndef CNOID_GLVISIONSIMULATORPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_GLVISIONSIMULATORPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_GLVISIONSIMULATORPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_GLVISIONSIMULATORPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_GLVISIONSIMULATORPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_GLVISIONSIMULATORPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_GLVISIONSIMULATORPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_GLVISIONSIMULATORPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_GLVISIONSIMULATORPLUGIN_DLLIMPORT
#   define CNOID_GLVISIONSIMULATORPLUGIN_DLLEXPORT
#   define CNOID_GLVISIONSIMULATORPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_GLVISIONSIMULATORPLUGIN_STATIC
#  define CNOID_GLVISIONSIMULATORPLUGIN_DLLAPI
#  define CNOID_GLVISIONSIMULATORPLUGIN_LOCAL
# else
#  ifdef CnoidGLVisionSimulatorPlugin_EXPORTS
#   define CNOID_GLVISIONSIMULATORPLUGIN_DLLAPI CNOID_GLVISIONSIMULATORPLUGIN_DLLEXPORT
#  else
#   define CNOID_GLVISIONSIMULATORPLUGIN_DLLAPI CNOID_GLVISIONSIMULATORPLUGIN_DLLIMPORT
#  endif
#  define CNOID_GLVISIONSIMULATORPLUGIN_LOCAL CNOID_GLVISIONSIMULATORPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_GLVISIONSIMULATORPLUGIN_DLLAPI
