  
#ifndef CNOID_PYTHON3PLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_PYTHON3PLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_PYTHON3PLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_PYTHON3PLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_PYTHON3PLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_PYTHON3PLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_PYTHON3PLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_PYTHON3PLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_PYTHON3PLUGIN_DLLIMPORT
#   define CNOID_PYTHON3PLUGIN_DLLEXPORT
#   define CNOID_PYTHON3PLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_PYTHON3PLUGIN_STATIC
#  define CNOID_PYTHON3PLUGIN_DLLAPI
#  define CNOID_PYTHON3PLUGIN_LOCAL
# else
#  ifdef CnoidPython3Plugin_EXPORTS
#   define CNOID_PYTHON3PLUGIN_DLLAPI CNOID_PYTHON3PLUGIN_DLLEXPORT
#  else
#   define CNOID_PYTHON3PLUGIN_DLLAPI CNOID_PYTHON3PLUGIN_DLLIMPORT
#  endif
#  define CNOID_PYTHON3PLUGIN_LOCAL CNOID_PYTHON3PLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_PYTHON3PLUGIN_DLLAPI
