/**
   The following header and the corresponding .c file were generated by OpenGL Loader Generator (glLoadGen)
   with the command: lua LoadGen.lua -style=pointer_c -spec=gl -version=3.3 -profile=core core_3_3 or
                     lua LoadGen.lua -style=pointer_c -spec=gl -version=4.0 -profile=core core_4_0.
                     lua LoadGen.lua -style=pointer_c -spec=gl -version=4.4 -profile=core core_4_4.
*/
#include "gl_core_3_3.h"
#define CNOID_GL_CORE_3_3

//#include "gl_core_4_0.h"
//#define CNOID_GL_CORE_4_0

//#include "gl_core_4_4.h"
//#define CNOID_GL_CORE_4_4
