#ifndef CNOID_AGXDYNAMICSPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_AGXDYNAMICSPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_AGXDYNAMICSPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_AGXDYNAMICSPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_AGXDYNAMICSPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_AGXDYNAMICSPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_AGXDYNAMICSPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_AGXDYNAMICSPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_AGXDYNAMICSPLUGIN_DLLIMPORT
#   define CNOID_AGXDYNAMICSPLUGIN_DLLEXPORT
#   define CNOID_AGXDYNAMICSPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_AGXDYNAMICSPLUGIN_STATIC
#  define CNOID_AGXDYNAMICSPLUGIN_DLLAPI
#  define CNOID_AGXDYNAMICSPLUGIN_LOCAL
# else
#  ifdef CnoidAGXDynamicsPlugin_EXPORTS
#   define CNOID_AGXDYNAMICSPLUGIN_DLLAPI CNOID_AGXDYNAMICSPLUGIN_DLLEXPORT
#  else
#   define CNOID_AGXDYNAMICSPLUGIN_DLLAPI CNOID_AGXDYNAMICSPLUGIN_DLLIMPORT
#  endif
#  define CNOID_AGXDYNAMICSPLUGIN_LOCAL CNOID_AGXDYNAMICSPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_AGXDYNAMICSPLUGIN_DLLAPI
